import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";


// const montSerrat = Montserrat({
//   display: "swap",
//   subsets: ["latin"],
//   variable: "--font-monserrat",
//   weight: "900"
// })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
